/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomTooltip: typeof import('./src/components/common/CustomTooltip.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAlertCircle: typeof import('~icons/mdi/alert-circle')['default']
    IMdiArrowUp: typeof import('~icons/mdi/arrow-up')['default']
    IMdiCalendarClock: typeof import('~icons/mdi/calendar-clock')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCloseCircle: typeof import('~icons/mdi/close-circle')['default']
    IMdiDiscord: typeof import('~icons/mdi/discord')['default']
    IMdiFileDocument: typeof import('~icons/mdi/file-document')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiHelpCircle: typeof import('~icons/mdi/help-circle')['default']
    IMdiHistory: typeof import('~icons/mdi/history')['default']
    IMdiLicense: typeof import('~icons/mdi/license')['default']
    IMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IMdiPuzzleOutline: typeof import('~icons/mdi/puzzle-outline')['default']
    IMdiQq: typeof import('~icons/mdi/qq')['default']
    IMdiQqchat: typeof import('~icons/mdi/qqchat')['default']
    IMdiRefresh: typeof import('~icons/mdi/refresh')['default']
    IMdiTag: typeof import('~icons/mdi/tag')['default']
    IMdiTagMultiple: typeof import('~icons/mdi/tag-multiple')['default']
    IMdiTagOff: typeof import('~icons/mdi/tag-off')['default']
    IMdiTagOutline: typeof import('~icons/mdi/tag-outline')['default']
    IMdiTextBoxOutline: typeof import('~icons/mdi/text-box-outline')['default']
    IMdiWeb: typeof import('~icons/mdi/web')['default']
    PluginCard: typeof import('./src/components/plugin-store/PluginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
